services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    image: dbt-trino
    container_name: dbt-trino
    restart: no
    networks:
      - frostbyte-net
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    volumes:
      - ./profiles:/root/.dbt
    command: ["--help"]
