services:
  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    image: dbt-trino
    restart: no
    networks:
      - frostbyte-net
    volumes:
      - ./profiles:/root/.dbt
    command: ["--help"]
