FROM metabase/metabase:v0.57.10

RUN wget https://github.com/starburstdata/metabase-driver/releases/download/6.1.0/starburst-6.1.0.metabase-driver.jar \
    -O /plugins/starburst-6.1.0.metabase-driver.jar
