include:
  - path: ./airflow/compose.yml
  - path: ./dbt/compose.yml
  - path: ./metabase/compose.yml
  - path: ./minio/compose.yml
  - path: ./postgres/compose.yml
  - path: ./trino/compose.yml

volumes:
  postgres-data:
  minio-data:

networks:
  frostbyte-net:
    driver: bridge
