olist_project:
  outputs:
    dev:
      type: trino
      method: none
      user: ahmed
      database: iceberg
      host: trino-coordinator
      port: 8080
      schema: raw
      threads: 1

  target: dev
